// src/routes/params.js

export const bibleBooks = {
	gen: { name: 'Genesis', chapters: 50, versesPerChapter: [31, 25, 24] },
	exo: { name: 'Exodus', chapters: 40, versesPerChapter: [22, 25, 22 /* remaining chapters */] },

	gen: 'Genesis',
	exo: 'Exodus',
	lev: 'Leviticus',
	num: 'Numbers',
	deut: 'Deuteronomy',
	josh: 'Joshua',
	judg: 'Judges',
	ruth: 'Ruth',
	sam1: '1 Samuel',
	sam2: '2 Samuel',
	kgs1: '1 Kings',
	kgs2: '2 Kings',
	chr1: '1 Chronicles',
	chr2: '2 Chronicles',
	ezra: 'Ezra',
	neh: 'Nehemiah',
	esth: 'Esther',
	job: 'Job',
	psa: 'Psalms',
	prov: 'Proverbs',
	eccl: 'Ecclesiastes',
	song: 'Song of Solomon',
	isa: 'Isaiah',
	jer: 'Jeremiah',
	lam: 'Lamentations',
	ezek: 'Ezekiel',
	dan: 'Daniel',
	hos: 'Hosea',
	joel: 'Joel',
	amos: 'Amos',
	obad: 'Obadiah',
	jonah: 'Jonah',
	mic: 'Micah',
	nah: 'Nahum',
	hab: 'Habakkuk',
	zeph: 'Zeph',
	hag: 'Haggai',
	zech: 'Zechariah',
	mal: 'Malachi',
	matt: 'Matthew',
	mark: 'Mark',
	luke: 'Luke',
	john: 'John',
	acts: 'Acts',
	rom: 'Romans',
	cor1: '1 Corinthians',
	cor2: '2 Corinthians',
	gal: 'Galatians',
	eph: 'Ephesians',
	phil: 'Philippians',
	col: 'Colossians',
	thess1: '1 Thessalonians',
	thess2: '2 Thessalonians',
	tim1: '1 Timothy',
	tim2: '2 Timothy',
	// finish this list
	tit: 'Titus',
	phil: 'Philemon',
	heb: 'Hebrews',
	jam: 'James',
	pet1: '1 Peter',
	pet2: '2 Peter',
	john1: '1 John',
	john2: '2 John',
	john3: '1 John',
	jud: 'Jude',
	rev: 'Revelation'
};
